### ISSUE TITLE
layout test fail on `class Base {   int a;   bool b; };  class Foo : public Base {   bool c; };`

### ISSUE THREAD

**Issue by kkimdev** [servo/rust-bindgen#404] opened 2017-01-18 19:39 UTC
C++ header:
```C++
class Base {
  int a;
  bool b;
};

class Foo : public Base {
  bool c;
};
```

Generated test:
```Rust
#[test]
fn bindgen_test_layout_Foo() {
    assert_eq!(::std::mem::size_of::<Foo>() , 8usize);
    assert_eq!(::std::mem::align_of::<Foo>() , 4usize);
}
```

Test output:
```
'assertion failed: `(left == right)` (left: `12`, right: `8`)',
```

Please let me know in case it's not reproducible.

**Comment by emilio** [comment] 2017-01-18 23:45
Yup, this is a dupe of #380, thanks for reporting it. My intuition is that solving this for code without template parameters may be relatively straight-forward, but with templates we need to be more careful.

Going to close this as a dupe, but I have it on my radar.

Thanks again for reporting it! :)

**Closed by emilio** 2017-01-18 23:45 UTC

**Comment by fitzgen** [comment] 2017-01-19 15:43
Also, thanks for the descriptive and concise bug report :)
