### ISSUE TITLE
can't find C++ constructors

### ISSUE THREAD

**Issue by ctaggart** [servo/rust-bindgen#714] opened 2017-05-22 10:08 UTC
The ovl.h header file for Octave Value List has multiple constructors, but I can't find them in the generated rust code. I only see one `new` function. The one I need to use right now is the void constructor with no args. Any idea what I need to do it have it generate functions for the other constructors?

from https://github.com/NexMirror/Octave/blob/master/libinterp/octave-value/ovl.h
``` c
  octave_value_list (void)
    : data (), names () { }

  explicit octave_value_list (octave_idx_type n)
    : data (dim_vector (1, n)), names () { }

  octave_value_list (octave_idx_type n, const octave_value& val)
    : data (dim_vector (1, n), val), names () { }

  octave_value_list (const octave_value& tc)
    : data (dim_vector (1, 1), tc), names () { }

  template<template <typename...> class OV_Container>
  octave_value_list (const OV_Container<octave_value>& args)
    : data (args, dim_vector (1, args.size ())), names () { }

  octave_value_list (const Array<octave_value>& d)
    : data (d.as_row ()), names () { }

  octave_value_list (const Cell& tc)
    : data (tc.as_row ()), names () { }

  octave_value_list (const octave_value_list& obj)
    : data (obj.data), names (obj.names) { }

  // Concatenation constructor.
  octave_value_list (const std::list<octave_value_list>&);
```

from https://raw.githubusercontent.com/ctaggart/octh/master/src/lib.rs
``` rust 
  extern "C" {
        #[link_name = "_ZN17octave_value_listC1ERKSt4listIS_SaIS_EE"]
        pub fn octave_value_list_octave_value_list(this:
                                                       *mut root::octave_value_list,
                                                   arg1:
                                                       *const [u64; 2usize]);
    }
    impl Clone for octave_value_list {
        fn clone(&self) -> Self { *self }
    }
    impl octave_value_list {
        #[inline]
        pub unsafe fn prepend(&mut self, val: *const root::octave_value)
         -> *mut root::octave_value_list {
            octave_value_list_prepend(self, val)
        }
        #[inline]
        pub unsafe fn append(&mut self, val: *const root::octave_value)
         -> *mut root::octave_value_list {
            octave_value_list_append(self, val)
        }
        #[inline]
        pub unsafe fn append1(&mut self, lst: *const root::octave_value_list)
         -> *mut root::octave_value_list {
            octave_value_list_append1(self, lst)
        }
        #[inline]
        pub unsafe fn reverse(&mut self) -> *mut root::octave_value_list {
            octave_value_list_reverse(self)
        }
        #[inline]
        pub unsafe fn splice(&self, offset: root::octave_idx_type,
                             len: root::octave_idx_type,
                             lst: *const root::octave_value_list)
         -> root::octave_value_list {
            octave_value_list_splice(self, offset, len, lst)
        }
        #[inline]
        pub unsafe fn all_strings_p(&self) -> bool {
            octave_value_list_all_strings_p(self)
        }
        #[inline]
        pub unsafe fn all_scalars(&self) -> bool {
            octave_value_list_all_scalars(self)
        }
        #[inline]
        pub unsafe fn any_cell(&self) -> bool {
            octave_value_list_any_cell(self)
        }
        #[inline]
        pub unsafe fn has_magic_colon(&self) -> bool {
            octave_value_list_has_magic_colon(self)
        }
        #[inline]
        pub unsafe fn make_argv(&self, arg1: *const root::std::string)
         -> root::string_vector {
            octave_value_list_make_argv(self, arg1)
        }
        #[inline]
        pub unsafe fn make_storable_values(&mut self) {
            octave_value_list_make_storable_values(self)
        }
        #[inline]
        pub unsafe fn new(arg1: *const [u64; 2usize]) -> Self {
            let mut __bindgen_tmp = ::std::mem::uninitialized();
            octave_value_list_octave_value_list(&mut __bindgen_tmp, arg1);
            __bindgen_tmp
        }
    }
```

More details in https://github.com/ctaggart/octh/issues/18#issuecomment-303043814. It looks like https://github.com/servo/rust-bindgen/issues/334 may be related.

**Comment by emilio** [comment] 2017-05-22 10:13
Not really, this is known, and it's because the constructor is inline, so it generates no symbols, so there's no way we can call that from rust unfortunately.

See https://github.com/servo/rust-bindgen/issues/348 for more details, closing this as a dupe of it.

**Closed by emilio** 2017-05-22 10:13 UTC

**Comment by ctaggart** [comment] 2017-05-22 11:34
Thanks @emilio. It makes more sense, but I'm not sure what the recommended work-a-round is. Must I create a C++ dll that exposes the functions in a way that Rust can consume them? Is there any Rust only work-a-round?

**Comment by emilio** [comment] 2017-05-22 14:48
So unfortunately there isn't a rust-only workaround, in the sense that you can't call into a function that isn't there.

A solution for this could be something like compiling a static library with the symbols using `-fno-inline-functions`, and linking it into rust.

But at that point you might as well expose explicit functions for that a la:

```c++
extern "C" octave_value_list_create_0(octave_value_list* list) {
    new (list) octave_value_list();
}
```

That can be done entirely from Cargo's build script, see for example [our integration tests' script](https://github.com/servo/rust-bindgen/blob/master/bindgen-integration/build.rs#L23)

**Comment by ctaggart** [comment] 2017-05-23 06:17
Thanks @emilio, that is really helpful!

**Comment by ctaggart** [comment] 2017-06-07 09:23
@emilio, Any change you (or know someone who) could look at my [latest build errors](https://github.com/ctaggart/octh/issues/18#issuecomment-306041225)? It is blocking me from making progress on getting Rust to work for Octave. The .o file compiled with C++ ends up missing references when linked. Looking for any suggestions.

**Comment by ctaggart** [comment] 2017-09-25 12:07
I did as @emilio suggested and created an explicit function, but I'm not sure yet how to use it from Rust. I just want to create and return a new list, but this doesn't work. It complains about `cannot move out a dereference of raw pointer`. I'm still a rust newbie.

``` rust
pub unsafe extern "C"  fn Fhelloworld (args: *const octh::root::octave_value_list, nargout: ::std::os::raw::c_int) -> octh::root::octave_value_list {
    let list: *mut octh::root::octave_value_list = ::std::ptr::null_mut();
    octh::root::octave_value_list_new(list);
    std::mem::forget(list);
    return *list;
}
```

https://github.com/ctaggart/octh/pull/24

**Comment by ctaggart** [comment] 2017-09-25 15:31
I asked on stackoverflow and was given an answer that looks like it may work.
https://stackoverflow.com/questions/46407560/how-to-create-and-return-a-c-struct-from-rust-ffi
