### ISSUE TITLE
libbindgen::ir::ty: unsupported type: kind = CXTypeKind(118)

### ISSUE THREAD

**Issue by jsgf** [servo/rust-bindgen#351] opened 2016-12-21 02:25 UTC
I'm getting an error trying to parse:

```
template <class Char> class fbstring_core {
protected:
//...
  static constexpr auto kIsLittleEndian =
      __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__;
//...
};
```

(full source https://github.com/facebook/folly/blob/master/folly/FBString.h#L320)

which fails with:

```
ERROR:libbindgen::ir::ty: unsupported type: kind = CXTypeKind(118); ty = Type(const bool, kind: Auto, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor(
kind: NoDeclFound, loc: builtin definitions, usr: None)); at Some(Cursor(kIsLittleEndian kind: VarDecl, loc: third-party-buck/gcc-4.9-glibc-2.20-fb/build/libgcc/include/c++/trunk/bits/basi
c_fbstring.h:317:25, usr: Some("c:@N@std@ST>1#T@fbstring_core@kIsLittleEndian")))
thread 'main' panicked at 'Unable to resolve constant type?: Continue', /home/engshare/third-party2/rust/1.13/src/rust/src/libcore/result.rs:799
```

I'm using llvm-4.0 (ie, a dev snapshot), which I'm told should be close to 3.9.

Is there a straightforward workaround for this? I'm not actually interested in this type for my Rust ffi; I just need to get past it.

**Comment by fitzgen** [comment] 2016-12-21 18:00
> Is there a straightforward workaround for this? I'm not actually interested in this type for my Rust ffi; I just need to get past it.

You can try to `--blacklist-type "folly::fbstring_core"` (or equivalently `Builder::hide_type("folly::fbstring_core")` if you're using `libbindgen` directly). However, I can't remember if blacklisting causes us to skip parsing as well as codegen for the type, or only codegen.

**Comment by jsgf** [comment] 2016-12-21 18:08
Unfortunately that doesn't work. I'm using the command-line tool with:
```
bindgen --output ffi.rs --no-unstable-rust --blacklist-type folly::fbstring_core --generate functions     header.h -- -x c++ '-std=gnu++14' [...] -I...
```

and I get the same error. `--blacklist-type '.*'` is the same.

**Comment by emilio** [comment] 2016-12-21 18:14
Yeah, blacklisting doesn't stop us from trying to parse it, that is by design. Working on a fix.

BTW, if you're using a 4.0 snapshot, please ensure that it contains the patch over https://reviews.llvm.org/D26907 (was merged not too long ago), because otherwise a lot of your template parameters wont work.

**Closed** 2016-12-21 19:25 UTC
