### ISSUE TITLE
bindgen_test_layout_max_align_t fails

### ISSUE THREAD

**Issue by saurvs** [servo/rust-bindgen#605] opened 2017-04-01 14:30 UTC
### Input C Header

```C
// contents can be found at github.com/lxc/lxc/blob/master/src/lxc/lxccontainer.h
#include <lxc/lxccontainer.h>
```

### Bindgen Invokation

```Rust
let bindings = bindgen::Builder::default()
        .no_unstable_rust()
        .header("wrapper.h")
        .generate()
        .expect("Unable to generate lxc bindings");
```
### Actual Results
Output from `cargo test`
```
failures:

---- bindgen_test_layout_max_align_t stdout ----
	thread 'bindgen_test_layout_max_align_t' panicked at 'assertion failed: `(left == right)` (left: `24`, right: `32`): Size of: max_align_t', /home/saurav/lxc-rs/target/debug/build/lxc-5edc7f91e15740c0/out/bindings.rs:270
note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:
    bindgen_test_layout_max_align_t

test result: FAILED. 45 passed; 1 failed; 0 ignored; 0 measured
```
### Expected Results
All tests passing?

**Comment by emilio** [comment] 2017-04-02 12:16
dupe of https://github.com/servo/rust-bindgen/issues/550, thanks for reporting it!

**Closed by emilio** 2017-04-02 12:16 UTC
