### ISSUE TITLE
bindgen_test_layout_max_align_t ... FAILED

### ISSUE THREAD

**Issue by Dushistov** [servo/rust-bindgen#577] opened 2017-03-12 15:05 UTC
### Input C/C++ Header

```C++
// Define 'max_align_t' to match the GCC definition.
typedef struct {
  long long __clang_max_align_nonce1
      __attribute__((__aligned__(__alignof__(long long))));
  long double __clang_max_align_nonce2
      __attribute__((__aligned__(__alignof__(long double))));
} max_align_t;
```
I take it from llvm/clang header.

### Bindgen Invokation

```
$ bindgen --no-unstable-rust test.h 
```
### Actual Results

```rust
#[repr(C)]
#[derive(Debug, Copy)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: f64,
}
```

```
test gen_c::bindgen_test_layout_max_align_t ... FAILED

failures:

---- gen_c::bindgen_test_layout_max_align_t stdout ----
        thread 'gen_c::bindgen_test_layout_max_align_t' panicked at 'assertion failed: `(left == right)` (left: `24`, right: `32`): Size of: max_align_t', gen_c.rs:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    gen_c::bindgen_test_layout_max_align_t

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured
```

### Expected Results

All generated tests should be "green".

$ bindgen --version
bindgen 0.22.1

I also tried 1320efeb79d373acb8dd92fb2722732c251497d8, but it also generate failed test.

**Comment by emilio** [comment] 2017-03-12 15:12
Right, this is a dupe of https://github.com/servo/rust-bindgen/issues/550. See there for workarounds. Thanks for reporting!

**Closed by emilio** 2017-03-12 15:12 UTC

**Comment by philn** [comment] 2019-02-21 16:05
The link is 404 though. I'm also getting this issue :/

**Comment by traviscross** [comment] 2019-02-21 18:31
The correct link is now: #550

The underlying issue was apparently fixed.  However, the fix relies on the final build being done with a recent version of `rustc`, so we need to promise `bindgen` that we'll use such a version.  E.g.:

```rust
Builder::default()
  .rust_target(bindgen::RustTarget::Stable_1_28)
```
