### ISSUE TITLE
Additional padding on windows

### ISSUE THREAD

**Issue by Dushistov** [servo/rust-bindgen#553] opened 2017-03-03 08:40 UTC
### Versions

On both machines bindgen commit d57616cab66e6bfa6ddf745e57644c671bf57cd4
On windows machine: clang 3.9.0
On linux machine: 3.8.1

### Input C/C++ Header

```C++
union jvalue {
  float   f;
  double  d;
};
```

### Bindgen Invokation

```
$ bindgen --no-unstable-rust input.h 
```

### Actual Results

```rust
#[repr(C)]
#[derive(Debug, Copy)]
pub struct jvalue {
    pub f: __BindgenUnionField<f32>,
    pub __bindgen_padding_0: u32,
    pub d: __BindgenUnionField<f64>,
    pub bindgen_union_field: u64,
}
```

```
test bindgen_test_layout_jvalue ... FAILED

failures:

---- bindgen_test_layout_jvalue stdout ----
        thread 'bindgen_test_layout_jvalue' panicked at 'assertion failed: `(lef
t == right)` (left: `16`, right: `8`): Size of: jvalue', lib.rs:37
note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:
    bindgen_test_layout_jvalue

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

error: test failed
```

### Expected Results

On linux machine bindgen not generate `pub __bindgen_padding_0: u32,`
and add 
```
assert_eq! (::std::mem::align_of::<jvalue>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( jvalue ) ));
```
to test code,

This is only difference between code generated by bindgen (d57616cab66e6bfa6ddf745e57644c671bf57cd4) on both machines.

**Comment by emilio** [comment] 2017-03-03 13:26
huh, why are we padding unions anyway?

Thanks for the report.

**Comment by emilio** [comment] 2017-03-03 13:35
Can you paste your log with `RUST_LOG=codegen::struct_layout` on windows? A fix is disabling padding for unions, but I wonder what offset are we getting from clang anyway, given I can't reproduce with `-target x86_64-pc-windows-msvc` nor `-target i386-pc-windows-msvc`?

**Comment by emilio** [comment] 2017-03-03 13:39
Can you verify #554 fixes it?

**Comment by Dushistov** [comment] 2017-03-03 14:34
> Can you paste your log with RUST_LOG=codegen::struct_layout on windows? A fix is disabling padding for unions, but I wonder what offset are we getting from clang anyway, given I can't reproduce with -target x86_64-pc-windows-msvc nor -target i386-pc-windows-msvc?

```
: Offset: <padding>: 0 -> 0
: align field f to 0/0 with 0 padding bytes Layout { size: 4, align: 4, packed: false }
: Offset: f: 0 -> 4
: align_to_bitfield? false: Layout { size: 4, align: 4, packed: false } Layout { size: 8, align: 8, packed: false }
: Offset: <padding>: 4 -> 8
: align field d to 8/0 with 4 padding bytes Layout { size: 8, align: 8, packed: false }
: Offset: d: 8 -> 16
: align_to_bitfield? false: Layout { size: 8, align: 8, packed: false } Layout { size: 8, align: 8, packed: false }

```

**Comment by Dushistov** [comment] 2017-03-03 14:46
>Can you verify #554 fixes it?

At now generated code passed generated tests.

I also add   `assert_eq!(8, ::std::mem::align_of::<jvalue>());` and it also passed this tests,
so I close this bug?

**Comment by emilio** [comment] 2017-03-03 16:09
Let's close this when #554 lands :)

**Closed** 2017-03-03 17:51 UTC
