### ISSUE TITLE
clangll.rs -> clang_sys

### ISSUE THREAD

**Issue by Yamakaky** [servo/rust-bindgen#86] opened 2016-10-14 14:05 UTC

**Comment by emilio** [comment] 2016-10-14 16:46
This is basically a dupe of https://github.com/servo/rust-bindgen/issues/55. I'll reword the title there to be more clear.

Let me know if you're working on this, would be really appreciated! :)

**Closed by emilio** 2016-10-14 16:46 UTC

**Comment by Yamakaky** [comment] 2016-10-14 18:40
Oh, I'm sorry.

No, I'm not.
