### ISSUE TITLE
stylo bindings busted on UniquePtr

### ISSUE THREAD

**Issue by bholley** [servo/rust-bindgen#286] opened 2016-11-21 06:01 UTC
I bisected this down to #281.

The broken line in question comes from UniquePtr.h:

>pub type mozilla_UniquePtr_Pointer = typename detail::PointerType<T, DeleterType>::Type;

CC @fitzgen @emilio @heycam @manishearth @upsuper

**Comment by upsuper** [comment] 2016-11-21 07:16
The following code is enough to reproduce this bug:
```c++
namespace detail {
  template<typename T>
  struct PointerType {
    typedef T* Type;
  };
}
template<typename T>
class UniquePtr {
  typedef typename detail::PointerType<T>::Type Pointer;
};
```

rust-bindgen generates:
```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct detail_PointerType<T> {
    pub _address: u8,
    pub _phantom_0: ::std::marker::PhantomData<T>,
}
pub type detail_PointerType_Type<T> = *mut T;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UniquePtr<T> {
    pub _address: u8,
    pub _phantom_0: ::std::marker::PhantomData<T>,
}
pub type UniquePtr_Pointer = typename detail::PointerType<T>::Type;
```

**Comment by upsuper** [comment] 2016-11-21 07:21
Looks like `detail::PointerType<T>::Type` is an unexposed type. We probably need to skip it.

The issue here is not limited to the wrong type. We would also need to handle the new namespace prefix.

**Comment by upsuper** [comment] 2016-11-21 07:39
I guess if #287 can be fixed, we can just enable namespaces, and insert raw lines like
```rust
pub use root::*;
pub use root::mozilla::*;
```
so that the majority of existing code wouldn't need any update.

**Comment by emilio** [comment] 2016-11-21 08:36
Yeah, to be clear this is a bug that was exposed by #281, not created by it. With #281 the two items had the same name so we didn't generate the first one. Looking into this.

Also, good catch with #287, should be easy-ish to fix.

**Comment by emilio** [comment] 2016-11-22 09:30
Should be partially fixed with https://github.com/servo/rust-bindgen/pull/288. See that pull request for discussion. In any case shouldn't generate invalid output now.

**Closed by emilio** 2016-11-22 09:30 UTC
